config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # 
  resources :pictures
  get '/', to: "pictures#index", as: 'root'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

	def index
		@pictures = Picture.all
	end

	def new
		@picture = Picture.new
	end

	def create
		@picture = Picture.new(picture_params)
		if @picture.save
			redirect_to picture_path(@picture)
		else
			flash[:notice] = "The picture and info you entered is not valid. Please try again."
      		redirect_to new_picture_path
		end
	end

	def show
		@picture = Picture.find(params[:id])
	end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update
		@picture = Picture.find(params[:id])
		if @picture.update(picture_params)
			redirect_to picture_path(@picture)
		else
			flash[:notice] = "Update not valid. Try again."
			render :edit
		end
	end




	private

	def picture_params
      params.require(:picture).permit(:name, :description, :owner, :url)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResponsiveNone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav>
  <br>
  <h3>
	<%= link_to "Home", pictures_path %>  <a href="/pictures#mccarthy">McCarthy Family Photos</a>  <a href="/pictures#hasselbring">Hasselbring Family Photos</a>
	</h3>
	<br> <br>
	</nav>
    <%= yield %>
  </body>
</html>

app/views/pictures/index.html.erb
<h1>Family Pictures</h1>

<div>This page lists some random photos from the McCarthy family. They come from the last few years, they are from all over the world, and they include multi generations - of both humans and are beloved pets.</div>

<!-- looping through McCarthy pictures -->
<h3>McCarthy Family Pictures</h3>
<div id=mccarthy >
<% @pictures.each do |picture| %>
	<% if picture.id <= 6 %>
	<%= link_to image_tag("/assets/mccarthy/#{picture.url}", width: '500', alt: '#{picture.name}'), picture_path(picture) %>
	<% end %>
	<% end %>
</div>

<br>
<br>


<!-- looping through Hasselbring pictures -->
<div id=hasselbring >
<h3>Hasselbring Family Pictures</h3>
<% @pictures.each do |picture| %>
	<% if picture.id > 6 %>
	<%= link_to image_tag("/assets/hasselbring/#{picture.url}", width: '500', alt: '#{picture.name}'), picture_path(picture) %>
	<% end %>
	<% end %>
</div>

<br>
<br>

app/views/pictures/new.html.erb
<h1>Add Picture</h1>

<%= flash[:notice] %>

<%= form_for(@picture) do |f| %>

<%= f.label :name %><br>
<%= f.text_field :name %><br><br>

<%= f.label :description %><br>
<%= f.text_area :description %><br><br>

<%= f.label :owner %><br>
<%= f.text_field :owner %><br><br>

<%= f.label :url %><br>
<%= f.text_field :url %><br><br>


<%= f.submit  %>

		

<% end %>

app/views/pictures/show.html.erb
<%= link_to "Home", pictures_path %>

<h1>Picture Profile Page</h1>

<h3>
Name: <%= @picture.name %> <br>
Description: <%= @picture.description %> <br>
Owner: <%= @picture.owner %> <br>
URL:  <%= @picture.url %> <br>


<img alt="<%= @picture.name %>" src="/assets/<%= @picture.url %>" width="1000"/>